### ISSUE TITLE
Move Codes here from toshiba branch

### ISSUE THREAD

**Issue by KoukiHama** [eclipse-sw360/sw360-frontend#1]
https://github.com/toshiba/sw360/tree/dev/react-ui
https://github.com/eclipse/sw360/pull/1839

**Comment by tienlee** [comment]
We will refactor the login function (https://github.com/toshiba/sw360/tree/dev/react-ui) following Next.js solution, then commit it soon.

**Comment by hoangnt2** [comment]
Please assign me

**Comment by heliocastro** [comment]
@hoangnt2 I started to do this one, but then appreciate.

Please do me two favors then:

- Verify if you are already as a committer in the org repository ( you should )

- Follow one of this paths to develop:

(easy one): Have docker in your machine and use vscode. It will automatically create a container with latest Debian, with everything setup, and you don't need to change your operational system

If you use  a different editor, do this:
```bash
cd sw360-frontend
docker buildx build --tag sw360-frontend -f .devcontainer/Dockerfile .devcontainer
docker run -it --mount type=bind,source=$PWD,target=/workspace/sw360-frontend --workdir /workspace/sw360-frontend -p 3000:3000 --entrypoint /bin/bash sw360-frontend 
npm install -U
npm run dev
```

Or just install node 19 on your machine and code as usual

**Comment by heliocastro** [comment]
@hoangnt2 Ahh, i forgot, i enabled commitlint and husky
So, if you are using local devel, just run on your machine:
```bash
npm install commitlint husky
husky init
```
