### ISSUE TITLE
Progress: Fix eslint error

### ISSUE THREAD

**Issue by hoangnt2** [eclipse-sw360/sw360-frontend#335]
No| Item | Path | Status | PIC | Note |
-- | -- | -- | -- | -- | -- |
1 | Home Page + Auth Page | /src/app/[locale]/home | **DONE** | @hoangnt2 |  |
2 | Project Page | /src/app/[locale]/projects |  **DONE**  |  @deo002  |  |
3 | Component Page | /src/app/[locale]/components  | **DONE** | @hoangnt2 |  |
4 | License Page | /src/app/[locale]/licenses  | **DONE** | @hoangnt2 |  |
5 | ECC page | /src/app/[locale]/ecc |  **DONE** |  @hoangnt2  |  |
6 | Request page | /src/app/[locale]/requests | **IN PROGRESS**  |  @amritkv   |  |
7 | Search page | /src/app/[locale]/search |  **DONE**  |    @hoangnt2   |  |
8 | Preferences page | /src/app/[locale]/preferences  | **DONE** | @hoangnt2 |  |
9 | Vulnerabilities page | /src/app/[locale]/vulnerabilities |  **DONE**  |  @duonglq-tsdv  |  |
10 | Users page (ADMIN) | /src/app/[locale]/admin/users | **DONE**   | @deo002 |  |
11 | Licenses page (ADMIN) | /src/app/[locale]/admin/licenses |**DONE** | @duonglq-tsdv |  |
12 | Database Sanitation (ADMIN) | /src/app/[locale]/admin/databaseSanitation | **DONE**  |  @deo002  |  |
13 | Vendors page (ADMIN) | /src/app/[locale]/admin/vendors | **DONE**   | @deo002 |  |
14 | Common components | /src/components | **DONE**  | @hoangnt2 |  |
15 | Object types | /src/object-types | **DONE** | @hoangnt2  | |
16 | Services | /src/services | **DONE**  | @deo002  |  |
17 | Api Routes | /src/app/api | **DONE**  | @deo002  |  |
18 | Package Page | /src/app/[locale]/packages |  **DONE** | @duonglq-tsdv  |  |

**Comment by hoangnt2** [comment]
@heliocastro @amritkv @deo002,
I have listed all item we need to fix and their status. If you are fixing any items, please edit  table above to make it easier for others to follow

**Comment by hoangnt2** [comment]
@amritkv, @deo002, as I see in the above table, the **Request page** and **Api Routes** are marked as DONE.
But when I run `npm run lint ` on latest commit of main branch (8a137e7), I still see the errors. Did I miss something?

Request page:
![image](https://github.com/user-attachments/assets/36164994-d155-4a03-8d22-3b7832d41f7f)


Api Routes:
![image](https://github.com/user-attachments/assets/dd81d1f3-1aad-4334-b507-db1761ea2767)

**Comment by amritkv** [comment]
> @amritkv, @deo002, as I see in the above table, the **Request page** and **Api Routes** are marked as DONE. But when I run `npm run lint ` on latest commit of main branch ([8a137e7](https://github.com/eclipse-sw360/sw360-frontend/commit/8a137e7e7769da80058d8465ff48ff3db312f62a)), I still see the errors. Did I miss something?
> 
> Request page: ![image](https://private-user-images.githubusercontent.com/94659621/381015565-36164994-d155-4a03-8d22-3b7832d41f7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxOTAyNjEsIm5iZiI6MTczMDE4OTk2MSwicGF0aCI6Ii85NDY1OTYyMS8zODEwMTU1NjUtMzYxNjQ5OTQtZDE1NS00YTAzLThkMjItM2I3ODMyZDQxZjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDA4MTkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMDY1YjI1ZGQ4MjBmZDVlNGI4YWQzYzlhMzVhM2JjZDAwODExYzNkZDU3Mjk1NjlhM2Y0ZTY1M2U5ZjIwYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wvS6dkUWltjuHELRG-m07kDHrtXfQr8obaVuA_bXlYU)
> 
> Api Routes: ![image](https://private-user-images.githubusercontent.com/94659621/381014449-dd81d1f3-1aad-4334-b507-db1761ea2767.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxOTAyNjEsIm5iZiI6MTczMDE4OTk2MSwicGF0aCI6Ii85NDY1OTYyMS8zODEwMTQ0NDktZGQ4MWQxZjMtMWFhZC00MzM0LWI1MDctZGIxNzYxZWEyNzY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDA4MTkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NmEwOTUxOTc3ZGVkYzhkZjExMTEzMjQwMDdmOGNhMWJiNzY3NGY5NWM4OWM3OTVhYzExY2U3NDRkOWRjNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BLWCM8vTyHZ9xKZtjcbwtFCNwhOFeRsUCJkTs2cy84U)

Hey @hoangnt2 ! What I can see, there are few error like use of `any`, although I haven't used `any` type in `requests/components/Requests.tsx`
Need to cross-check these error. And moreover we all are using same version of linter right ?

**Comment by hoangnt2** [comment]
@amritkv I think we are using same version of linter. In `requests/components/Requests.tsx` file. The any error come from fetchData function:
![image](https://github.com/user-attachments/assets/6b904bb7-c849-4a00-81e3-2812c9bf5374)
Because response.json() will return any type

You can fix this error by convert it to EmbeddedModerationRequest as below 
![image](https://github.com/user-attachments/assets/9de6ffab-04fd-49c6-adb8-5f5a02531448)

I am not sure why VSCode does not show this error, the error only appears when I run the command ` npm run lint`

**Comment by deo002** [comment]
@hoangnt2 @amritkv VS Code didn't show these errors and I didn't run npm run lint. I'll update the list and start to work on it.

**Comment by amritkv** [comment]
> @amritkv I think we are using same version of linter. In `requests/components/Requests.tsx` file. The any error come from fetchData function: ![image](https://private-user-images.githubusercontent.com/94659621/381086012-6b904bb7-c849-4a00-81e3-2812c9bf5374.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNjk0MDUsIm5iZiI6MTczMDI2OTEwNSwicGF0aCI6Ii85NDY1OTYyMS8zODEwODYwMTItNmI5MDRiYjctYzg0OS00YTAwLTgxZTMtMjgxMmM5YmY1Mzc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDA2MTgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2MDRiNTU3NmNlNTc3NDRmNDQwNDNhNWYzMzYzYWI1ZDQxM2E5MTdmOGZkNDE3MmMzOTI5ODQ0NDBhM2MyOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qja133A30apgNnIurw3DO7HefARSSGbj7Jp__XJlGYE) Because response.json() will return any type
> 
> You can fix this error by convert it to EmbeddedModerationRequest as below ![image](https://private-user-images.githubusercontent.com/94659621/381086871-9de6ffab-04fd-49c6-adb8-5f5a02531448.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNjk0MDUsIm5iZiI6MTczMDI2OTEwNSwicGF0aCI6Ii85NDY1OTYyMS8zODEwODY4NzEtOWRlNmZmYWItMDRmZC00OWM2LWFkYjgtNWY1YTAyNTMxNDQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDA2MTgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiMjM4MTVhOGFiOGY1NzUwMmIyZjcwN2FhOTY4YTM1YWFiODFlMGEyMzMzOTM3ZmRjOTgzMTUxY2FmODMwY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yOEaBuZPNOs_Sjueof_AIqOhtZ278F1amn7Nl-fR94s)
> 
> I am not sure why VSCode does not show this error, the error only appears when I run the command ` npm run lint`

@hoangnt2 @deo002 Same for me as well. I'll fix VS Code and update the changes.

**Comment by hoangnt2** [comment]
@amritkv @deo002 thanks guys

**Comment by heliocastro** [comment]
@amritkv @deo002 VSCode show this errors

My settings for TS/JS ( Most important is ESLint ):
Plugins i use 
* Total Typescript -> Very good info for people that is not native js/ts developers 
* ESLint
* i18n Ally
* Prettier
* Prettify Typescript
* Rewrap
* Tailwind CSS Intellisense

And the config:
```json
"eslint.format.enable": true,
"eslint.debug": true,
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
      "source.fixAll.eslint": "always"
    }
  },
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
      "source.fixAll.eslint": "always"
    }
  },
  "[typescriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
      "source.fixAll.eslint": "always"
    }
  },
  "[javascriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
      "source.fixAll.eslint": "always"
    },
  "i18n-ally.indent": 4,
  "typescript.updateImportsOnFileMove.enabled": "always",
  "totalTypeScript.hideAllTips": false,
  "totalTypeScript.hideBasicTips": true,
  "totalTypeScript.hiddenTips": [
    "passing-generics-to-types",
    "tuple-type",
    "keyof",
    "typeof",
    "interface-with-generics",
    "interface-with-multiple-generics",
    "mapped-type",
    "readonly-utility-type",
    "record-utility-type"
  ],
  },
```

**Comment by heliocastro** [comment]
We are good now, typing now is warning, not error.
So we ill keep for now this way, just let's make some pact that we will solve warnings as long we found then.

**Comment by heliocastro** [comment]
Good to go....
