### ISSUE TITLE
Normalize the environment var for SW360 api

### ISSUE THREAD

**Issue by heliocastro** [eclipse-sw360/sw360-frontend#45]
We now have a confusion between environment vars.

@hoangnt2 set the env like this:
`src/utils/env.ts:export const SW360_API_URL: string | undefined  = process.env.NEXT_PUBLIC_SW360_API_URL;`

but @amritkv set then other parts as
`src/services/auth.service.ts:import { SW360_API_URL } from '@/utils/env';`

We need decide for a simple one.
@KoukiHama i assigned the bug to you since @hoangnt2 stil can't be assigned.

My vote will be keep SW360_API_URL.
@hoangnt2 @amritkv Please comment on that.

**Comment by amritkv** [comment]
@heliocastro Just to let you know, actually it was the other way that you mentioned. But my vote will also be for `SW360_API_URL`

**Comment by hoangnt2** [comment]
> We now have a confusion between environment vars.
> 
> @hoangnt2 set the env like this: `src/utils/env.ts:export const SW360_API_URL: string | undefined = process.env.NEXT_PUBLIC_SW360_API_URL;`
> 
> but @amritkv set then other parts as `src/services/auth.service.ts:import { SW360_API_URL } from '@/utils/env';`
> 
> We need decide for a simple one. @KoukiHama i assigned the bug to you since @hoangnt2 stil can't be assigned.
> 
> My vote will be keep SW360_API_URL. @hoangnt2 @amritkv Please comment on that.

**SW360_API_URL** can not be used in client component. So we need add prefix **NEXT_PUBLIC_**

**Comment by heliocastro** [comment]
Ok, so it's decided then :-)
NEXT_PUBLIC it is.
We love when the frameworks are opiniated.
Thanks @hoangnt2 and @amritkv
